# entrada
# CAPTURANDO O SALARIO E CONVERTENDO PARA FLOAT
SALARIO MENSAL = float(INPUT('INFORME O SEU SALARIO MENSAL:'))

# PROCESSAMENTO
SALARIO_ANUAL = SALARIO_MENSAL * 12

# SAIDA
print('SALARIO ANUAL: R$' , SALARIO_ANUAL)